services:
  documentation:
    image: squidfunk/mkdocs-material:latest
    container_name: mkdocs_graduationproject
    command: serve --dev-addr=0.0.0.0:2638 --watch-theme
    restart: unless-stopped
    ports:
      - "2638:2638"
    volumes:
      - ./documentation:/docs:ro

  local_database:
    image: postgres:16-alpine
    container_name: groupproject_database
    hostname: groupproject_database
    restart: always
    env_file:
      - .env
    ports:
      - "6652:${POSTGRES_PORT}"
    volumes:
      - postgres_datastorage_data:/var/lib/postgresql/data
    networks:
      - main_network

  backend_api:
    build:
      dockerfile: Dockerfile
      context: ./backend_api
    container_name: backend_api_course_project
    hostname: backend_api
    restart: always
    env_file:
      - .env
    volumes:
      - ./backend_api/app:/app
    ports:
      - "4321:4321"
    command: |
      sh -c "
      alembic upgrade head && \
      uvicorn main:app --port=4321 --host=0.0.0.0 --reload
      "
    networks:
      - main_network

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    container_name: frontend
    hostname: frontend
    restart: always
    env_file:
      - .env
    volumes:
      - ./frontend/app:/app
    ports:
      - "12346:12346"
    command: |
      sh -c "
      uvicorn main:app --port=12346 --host=0.0.0.0 --reload
      "
    networks:
      - main_network

  notification:
    build:
      dockerfile: Dockerfile
      context: ./notification_service
    container_name: notification
    hostname: notification
    restart: always
    env_file:
      - .env
    volumes:
      - ./notification_service/app:/app
    command: |
      sh -c "
      python /app/main.py
      "

  nginx_2:
    image: nginx:alpine
    container_name: nginx_2
    restart: always
    ports:
      - "80:80"
    networks:
      - main_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  main_network:
    driver: bridge

volumes:
  postgres_datastorage_data:
    external: false
