"""create new buildings table

Revision ID: 7afed28c0159
Revises: 9a93c3bcebd2
Create Date: 2025-06-29 15:21:48.067185

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7afed28c0159"
down_revision: Union[str, None] = "9a93c3bcebd2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_description"), table_name="products")
    op.drop_index(op.f("ix_products_title"), table_name="products")
    op.drop_table("products")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("uuid_data", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
        sa.Column("price", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.Column("main_image", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("images", postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("products_pkey")),
    )
    op.create_index(op.f("ix_products_title"), "products", ["title"], unique=False)
    op.create_index(op.f("ix_products_description"), "products", ["description"], unique=False)
    # ### end Alembic commands ###
